site_name: 苏方木的笔记
site_description: 苏方木的笔记
site_author: 苏方木
site_url: https://github.com/sufangmu/notes
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  language: 'zh'
  feature:
    tabs: true
    instant: true

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/sufangmu'
    - type: 'envelope-open'
      link: 'mailto:sufangmu8377@163.com'
  search:
    tokenizer: '[\s\-\.]+' 
    prebuild_index: true  
plugins:
  - search
  - progress
  - git-revision-date-localized
nav:
  - '首页': 'index.md'
  - Linux:
    - '常用命令': 'linux/linux_commands.md'
    - '文本处理三剑客': 'linux/grep_sed_awk.md'
    - '服务': 'linux/service.md'
    - '网络': 'linux/network/iptables.md'
    - '编辑器': 'linux/vim.md'
  - 数据库:
    - mysql: 
      - '基础': 'databases/MySQL/基础.md'
      - 'SQL': 'databases/MySQL/SQL.md'
      - '存储过程和函数': 'databases/MySQL/存储过程和函数.md'
      - '索引': 'databases/MySQL/索引.md'
      - '执行计划': 'databases/MySQL/执行计划.md'
      - '日志': 'databases/MySQL/日志.md'
      - '优化': 'databases/MySQL/优化.md'
      - '运维': 'databases/MySQL/运维.md'

  - 前端:
      - 'HTTP': 'web/HTTP.md'      
      - 'RESTful': 'web/RESTful.md'      
      - 'HTML': 'web/html.md'
      - 'CSS': 'web/CSS.md'
      - 'JavaScript': 'web/JavaScript.md'
      - 'jQuery': 'web/jQuery.md'   
      - 'Nginx': 'web/Nginx.md'
      - 'Tomcat': 'web/Tomcat.md'
  - 编程语言:
    - 'Shell': 'language/ShellScript.md'
    - Python:
      - 'python简介': 'language/python/01-python简介.md'
      - '基本数据类型': 'language/python/02-基本数据类型.md'
      - '逻辑控制': 'language/python/03-逻辑控制.md'
      - '函数': 'language/python/04-函数.md'
      - '面向对象': 'language/python/05-面向对象.md'
      - '包和模块': 'language/python/06-包和模块.md'
      - '迭代和推导': 'language/python/07-迭代和推导.md'
      - '文件处理': 'language/python/08-文件处理.md'
      - '异常处理': 'language/python/09-异常与测试.md'
      - '内置模块': 'language/python/01-内置模块.md'
      - '并行编程': 'language/python/02-并发编程.md'
      - '网络编程': 'language/python/03-网络编程.md'
      - '数据库编程': 'language/python/04-数据库编程.md' 
      - 'Jinja2': 'language/python/Jinja2.md'
      - Django: 
        - '安装': 'language/python/Django/install.md'
        - '请求响应三板斧': 'language/python/Django/response.md'
        - '路由层': 'language/python/Django/urls.md'
        - '视图层': 'language/python/Django/view.md'
        - '模板层': 'language/python/Django/template.md'
        - '模型层': 'language/python/Django/model.md'
        - '中间件': 'language/python/Django/middleware.md'
        - '表单': 'language/python/Django/forms.md'
        - 'auth模块': 'language/python/Django/auth.md'
        - 'cookie和session': 'language/python/Django/cookie&session.md'
        - 'DjangoRESTframework':
          - '安装': 'language/python/Django/DjangoRESTframework/install.md'
  - 虚拟化:
    - Docker:
      - 'Docker基础': 'Virtualization/Docker/Docker基础.md'
    - Kubernetes:
      - 'Kubernetes基础':   'Virtualization/Kubernetes/k8s基础.md'
  - CI&CD:
    - 版本控制:
      - 'Git': 'CICD/Git/Git.md' 
    - Ansible: 
      - 'Ansible基础': 'CICD/Ansible/ansible.md'
    - Jenkins: 
      - 'Jenkins基础': 'CICD/Jenkins/Jenkins基础.md'
  - 资源:
      - '资源': 'resource/docs.md'
  - 音乐:
      - 'music/music.md'