site_name: 苏方木的笔记
site_description: 苏方木的笔记
site_author: 苏方木
site_url: https://github.com/sufangmu

theme:
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: 切换到明亮模式
      primary: light blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到深色模式
      primary: black
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: zh
  programming: zh
  features:
    - navigation.top  # 返回顶部
    - search.suggest # 查询建议
    - search.highlight
    - navigation.instant  # 即时加载
    - navigation.tracking  # 锚点跟踪
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true    
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes 
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:gaopeng0214@126.com
    - icon: fontawesome/brands/github
      link: https://github.com/sufangmu
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css      


plugins:
  - search:
      separator: '[\s\-\.]+'   
      lang: 
        - en
nav:
  - 首页: 'index.md'
  - Linux:
    - '命令行': 'linux/command-line.md'
    - '文本处理': 'linux/grep_sed_awk.md'
    - 'ShellScript': 'linux/ShellScript.md'
    - 'VIM': 'linux/vim.md'
    - '服务': 'linux/service.md'
    - 网络: 
      - 'TCP/IP': 'linux/network/TCP.md'
      - 'Iptables': 'linux/network/iptables.md'
    - '文档': 'linux/docs.md'  
  - 数据库:
    - MySQL: 
      - '安装': 'databases/MySQL/安装.md'
      - '用户管理': 'databases/MySQL/用户管理.md'
      - '数据类型和运算符': 'databases/MySQL/数据类型和运算符.md'
      - 'SQL': 'databases/MySQL/SQL.md'
      - '存储过程和函数': 'databases/MySQL/存储过程和函数.md'
      - '索引': 'databases/MySQL/索引.md'
      - '执行计划': 'databases/MySQL/执行计划.md'
      - 优化:
        - 'SQL优化': 'databases/MySQL/SQL优化.md'
        - '索引优化': 'databases/MySQL/索引优化.md'
  - 前端:
    - 协议:
      - 'HTTP': 'web/协议/HTTP.md'      
      - 'RESTful': 'web/协议/RESTful.md' 
    - 语言:
      - 'HTML': 'web/语言/html.md'
      - 'CSS': 'web/语言/CSS.md'
      - 'JavaScript': 'web/语言/JavaScript.md'
    - 框架:
      - 'jQuery': 'web/框架/jQuery.md'
    - 软件:
      - 'Nginx': 'web/软件/Nginx.md'
      - 'Tomcat': 'web/软件/Tomcat.md'
  - 编程语言:
    - Python:
      - 基础:
        - 'python简介': 'programming/python/基础/01-python简介.md'
        - '基本数据类型': 'programming/python/基础/02-基本数据类型.md'
        - '逻辑控制': 'programming/python/基础/03-逻辑控制.md'
        - '函数': 'programming/python/基础/04-函数.md'
        - '面向对象': 'programming/python/基础/05-面向对象.md'
        - '包和模块': 'programming/python/基础/06-包和模块.md'
        - '迭代和推导': 'programming/python/基础/07-迭代和推导.md'
        - '文件处理': 'programming/python/基础/08-文件处理.md'
        - '异常处理': 'programming/python/基础/09-异常与测试.md'
        - '内置模块': 'programming/python/基础/01-内置模块.md'
        - '并发编程': 'programming/python/基础/02-并发编程.md'
        - '网络编程': 'programming/python/基础/03-网络编程.md'
        - '数据库编程': 'programming/python/基础/04-数据库编程.md' 
      - Django: 
        - '安装': 'programming/python/Django/install.md'
        - '请求': 'programming/python/Django/request.md'
        - '响应三板斧': 'programming/python/Django/response.md'
        - '路由层': 'programming/python/Django/urls.md'
        - '视图层': 'programming/python/Django/view.md'
        - '模板层': 'programming/python/Django/template.md'
        - '模型层': 'programming/python/Django/model.md'
        - '中间件': 'programming/python/Django/middleware.md'
        - '表单': 'programming/python/Django/forms.md'
        - 'auth模块': 'programming/python/Django/auth.md'
        - 'cookie和session': 'programming/python/Django/cookie&session.md'
        - 'admin': programming/python/Django/admin.md
      - DRF:
        - '安装': 'programming/python/DRF/install.md'
        - '序列化': 'programming/python/DRF/序列化.md'
        - '请求和响应': 'programming/python/DRF/请求和响应.md'
        - '视图': 'programming/python/DRF/视图.md'
        - '路由': 'programming/python/DRF/路由.md'
        - '认证、权限和频率': 'programming/python/DRF/认证、权限和频率.md'
        - '过滤、排序、异常处理': 'programming/python/DRF/过滤、排序、异常处理.md'
        - '自定义response': 'programming/python/DRF/自定义response.md'
      - Flask:
        - '简介与安装': 'programming/python/Flask/install.md'
        - '配置': 'programming/python/Flask/configure.md'
        - '请求和响应': 'programming/python/Flask/request&response.md'
        - '路由': 'programming/python/Flask/route.md'
        - '模板': 'programming/python/Flask/template.md'
        - '视图': 'programming/python/Flask/view.md'
        - 'cookie和session': 'programming/python/Flask/cookie&session.md'
        - '蓝图': 'programming/python/Flask/blueprint.md'
        - '上下文': 'programming/python/Flask/context.md'
        - '闪现': 'programming/python/Flask/flashing.md'
        - '中间件': 'programming/python/Flask/middleware.md'
        - 扩展:
          - 'flask-session': 'programming\python\Flask\extention\flask-session.md'
        - 源码:
          - 'Local': 'programming/python/Flask/sourcecode/Local.md'
          - 'Session': 'programming/python/Flask/sourcecode/session.md'
          - 'Context': 'programming/python/Flask/sourcecode/context.md'
      - 'Jinja2': 'programming/python/Jinja2.md'
      - '数据分析': 'programming/python/数据分析/数据分析.md'
      - 测试:
        - '单元测试': 'programming/python/测试/单元测试.md'
    - Java:
      - 基础:
        - '概述': 'programming/java/基础/概述.md'
        - '语法': 'programming/java/基础/语法.md'
        - '数组': 'programming/java/基础/数组.md'
        - '面向对象（一）': 'programming/java/基础/面向对象（一）.md'
        - '面向对象（二）': 'programming/java/基础/面向对象（二）.md'
        - '面向对象（三）': 'programming/java/基础/面向对象（三）.md'
        - 'equals()和==': 'programming/java/基础/equals()和==.md'
        - '异常处理': 'programming/java/基础/异常处理.md'
      - 高级:
        - '多线程': 'programming/java/高级/多线程.md'
        - '常用类': 'programming/java/高级/常用类.md'
        - '枚举类': 'programming/java/高级/枚举类.md'
        - '泛型': 'programming/java/高级/泛型.md'
        - '集合': 'programming/java/高级/集合.md'
        - '反射': 'programming/java/高级/反射.md'
        - '注解': 'programming/java/高级/注解.md'
        - 'IO流': 'programming/java/高级/IO流.md'
        - '新特性': 'programming/java/高级/新特性.md'
      - JDBC: 'programming/java/JDBC/JDBC.md'
      - 设计模式: 'programming/java/设计模式.md'
    - 数据结构与算法:
      - '概述': 'programming/DataStructuresAndAlgorithms/数据结构与算法.md'
      - c:
        - "线性表": 'programming/DataStructuresAndAlgorithms/c/线性表.md'
  - 虚拟化:
    - Docker:
      - '实现': 'Virtualization/Docker/安装.md'
  - CI&CD:
    - 版本控制:
      - 'Git': 'CICD/Git/Git.md'
    - Jenkins:
      - 'pipeline-syntax': 'CICD/Jenkins/jenkins-pipeline-syntax.md'
      - 'jenkinsfile': 'CICD/Jenkins/jenkinsfile.md'
    - Ansible: 
      - 'Ansible基础': 'CICD/Ansible/ansible.md'
      - 'AnsibleAPI': 'CICD/Ansible/AnsibleAPI.md'
    - Jenkins: 
      - 'Jenkins基础': 'CICD/Jenkins/Jenkins基础.md'
  - 其他:
    - 中间件:
      - 'RabbitMQ': 'middleware/rabbitmq.md'
  - 资源:
      - '资源': 'resource/docs.md'
  - 音乐: 'music/music.md'