site_name: DevOps笔记
site_description: DevOps笔记
site_author: 高远志
site_url: https://github.com/yuanzhigao/devops-notes
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  language: 'zh'
  feature:
    tabs: true
    instant: true
markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - admonition
  
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/yuanzhigao'
    - type: 'envelope-open'
      link: 'mailto:gaopeng0214@126.com'
  search:
    tokenizer: '[\s\-\.]+'   
plugins:
  - search
  - progress
  - git-revision-date-localized
nav:
  - '主页': 'index.md'
  - Linux:
    - '常用命令': 'linux/linux_commands.md'
    - '文本处理三剑客': 'linux/文本处理三剑客.md'
    - '常用服务': 'linux/service.md'
    - 'IPtables': 'linux/iptables.md'
    - 'VIM': 'linux/vim.md'
  - 数据库:
    - '数据库基础': 'databases/数据库基础.md'
    - mysql: 
      - 'MySQL基础': 'databases/MySQL/MySQL基础.md'
      - 'MySQL进阶': 'databases/MySQL/MySQL进阶.md'
      - 'MySQL运维': 'databases/MySQL/MySQL运维.md'
  - WEB:
      - 'HTTP协议': 'web/HTTP.md'      
      - 'HTML': 'web/html.md'
      - 'CSS': 'web/CSS.md'
      - 'JavaScript': 'web/JavaScript.md'
      - 'jQuery': 'web/jQuery.md'   
      - 'Nginx': 'web/Nginx.md'
      - 'Tomcat': 'web/Tomcat.md'
  - 中间件:
      - 'RabbitMQ': 'software/middleware/rabbitmq.md'
  - 编程语言:
    - Shell: 
      - 'Shell': 'language/shell/shell.md'
    - Python:
      - 基础:
        - 'python简介': 'language/python/基础/01-python简介.md'
        - '基本数据类型': 'language/python/基础/02-基本数据类型.md'
        - '逻辑控制': 'language/python/基础/03-逻辑控制.md'
        - '函数': 'language/python/基础/04-函数.md'
        - '面向对象': 'language/python/基础/05-面向对象.md'
        - '包和模块': 'language/python/基础/06-包和模块.md'
        - '生成器与迭代器': 'language/python/基础/07-生成器与迭代器.md'
        - '文件处理': 'language/python/基础/08-文件处理.md'
        - '异常处理': 'language/python/基础/09-异常与测试.md'
      - 进阶:
        - '内置模块': 'language/python/进阶/01-内置模块.md'
        - '并行编程': 'language/python/进阶/02-并行编程.md'
        - '网络编程': 'language/python/进阶/03-网络编程.md'
        - '数据库编程': 'language/python/进阶/04-数据库编程.md'
        - web编程:    
          - 'Jinja2': 'language/python/进阶/web/Jinja2.md'   
          - 'Django': 'language/python/进阶/web/Django.md'
          - 'Flask': 'language/python/进阶/web/Flask.md'
  - 虚拟化:
    - Docker:
      - 'Docker基础': 'Virtualization/Docker/Docker基础.md'
    - Kubernetes:
      - 'Kubernetes基础':   'Virtualization/Kubernetes/k8s基础.md'
  - CI&CD:
    - 版本控制:
      - 'Git': 'CICD/Git/Git.md' 
    - Ansible: 
      - 'Ansible基础': 'CICD/Ansible/ansible.md'
    - Jenkins: 
      - 'Jenkins基础': 'CICD/Jenkins/Jenkins基础.md'
  - Docs:
      - '文档': 'resource/docs.md'